theme: jekyll-theme-minimal
title: Im9erius Homepage
description: This resource will be used to update projects and CTF's completed! 
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
