theme: jekyll-theme-minimal
title: IM9ERIUS Homepage
description: I am a Junior Cyber Security Analyst with a passion for technology and Blue Team operations. This resource will be used to showcase projects that I have completed
as well as my understanding of Blue Team activities. 
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
